### ISSUE TITLE
last.fm plugin

### ISSUE THREAD

**Issue by nukaskad** [DeaDBeeF-for-Windows/deadbeef#6]
Hello!
How I can to make (compile) a *.dll last.fm plugin???

**Comment by kuba160** [comment]
Hi,
last.fm plugin is currently not included in premake5 build, it needs to be 'ported' from Makefile.am to premake5 file. It looks fairly simple to do, so I'll try to do it in next few days. If there are no issues with compiling, I'll publish it so you can give it a try. Since I do not use last.fm, I would not be able to test it, so it would be great if you could let me know if it will work properly.

**Comment by kuba160** [comment]
Done! You can download the binary [here (lastfm.zip)](https://github.com/DeaDBeeF-for-Windows/deadbeef/files/2937166/lastfm.zip). I also made an account on last.fm and it looks like the plugin is working fine. Put the binary into plugins folder in your deadbeef directory or in `%APPDATA%\deadbeef\plugins`.
