### ISSUE TITLE
album art display

### ISSUE THREAD

**Issue by nukaskad** [DeaDBeeF-for-Windows/deadbeef#9]
Hello!
I try to display album artwork, but it dont working...

I do:
    1. Add new column, and choose the "Album Art" column type
    2. Right click on the playlist column headers, and in the context menu select "Group by" submenu. Click "Artist/Date/Album", or another option which you prefer.

How I can to display albums artwork in deadbeef for windows?

Deadbeef version: deadbeef-2019-06-08
OS: windows 10 x64

**Comment by kuba160** [comment]
It is not ported yet. I can't give you an estimate when this feature will be introduced in the windows version.

**Comment by kuba160** [comment]
Some progress has been done:
![image](https://user-images.githubusercontent.com/6359901/78464860-b9d10a00-76ee-11ea-89a7-ee0de26736a5.png)
For now only embedded cover art works (flac worked for me). I need to fix directory lookup.

I would also add there is second way to show album art, namely by using design mode.
Here is the plugin if you would like to test it.
[artwork-plugin-preview-2020-04-05.zip](https://github.com/DeaDBeeF-for-Windows/deadbeef/files/4432812/artwork-plugin-preview-2020-04-05.zip)
You will need latest deadbeef from april 2020. libjpeg-8.dll file has to be put in the directory where deadbeef executable is. artwork.dll goes into plugins directory.

**Comment by kuba160** [comment]
Artwork checklist before delivering:
- [x] Ensure cover gets loaded from all music files with embedded cover art. (all tested worked)
- [x] Loading artwork from local folders:
- - [x] Ensure cover gets loaded and shown
- [x] Test loading cover from internet sources
- - [ ] Last.fm and Albumart.org not working? check and compare to linux
- [x] Custom image when there is no cover found
- - [x] Ensure cover works consistently
- - [ ] Check if file picker can be replaced with native file chooser
- [x] UNC path artwork

Current state:
- Simple loading from directory and from embedded tags
- Last fm cover not working
- Downloading from music brains works

**Comment by Keith-Cancel** [comment]
I was looking at the album_art_wip branch this seems the legacy plugin correct me if I wrong? So I keep my covers all in the folders of each album instead embedding. So I looked the plugin and was trying to see what I would need to do get that working.

It appears to use a function pointer in `DB_vfs_t` for directory scanning so is it right to assume that is in the core application. Where would I look for it or I am complete off the mark to get this working? Like is more of an issue with reading/decoding?

**Comment by kuba160** [comment]
Yes, plugin is artwork_legacy. I recently made it working for embedded artworks. For separate covers when the plugin searches for cover it picks the first music file in directory. I think there is something wrong with wildcard. There is a change that cover with name that is first alphabetically in directory would load.

**Comment by Keith-Cancel** [comment]
So if you see my pull request I did get it working with files. Although I have noticed an other issue that seems to mostly be related to the cache-ing and how unix systems are utf8 based while Windows is utf16 based for encoding. I have a significant amount of Japanese music. So it became immediately obvious.

However, since I have been looking at the code for the plugin a little more closely I see some reasons as to why. For example in the jpeg_resize() function is using fopen and friends. These functions are pretty much only stuck to the ascii range on windows. Windows does have a utf16 versions of those functions such as _wfopen. It makes me think there maybe should be set of functions provided by the main app for file manipulation. Probably just a wrapper around the C style functions. That way on windows it can take the utf8 file paths and convert them to the utf16 equivalents. Just an idea, and it would make porting any other plugins easier in the future.

As you can see all the Mojibake.
![cache directory](https://user-images.githubusercontent.com/8355441/78744656-a70a3f80-7951-11ea-829c-6d1076c728c0.png)
 
However, for albums and paths with code points all in the ascii range no problem.
![cache dir2](https://user-images.githubusercontent.com/8355441/78744792-049e8c00-7952-11ea-8be5-4d7af48b9ea0.png)

Those with just ASCII range code points load fine, but anything else not so much.
![art](https://user-images.githubusercontent.com/8355441/78744867-2c8def80-7952-11ea-8c3f-c6c147cc1da3.png)

**Comment by Keith-Cancel** [comment]
It seems to be only some, part of me is wondering if it's maybe that some the embedded tag info might in shift JIS or something like that. Especially since I see that you made utf8 aware fopen in shared/windows.

**Comment by kuba160** [comment]
Album artwork was merged into master and is enabled by default. Current issues are:
- lastfm not working (MusicBrainz works)
- no native file selection for custom image when artwork is missing

**Comment by kuba160** [comment]
lastfm working with PR https://github.com/DeaDBeeF-Player/deadbeef/pull/2422. Closing the issue.
